**Pandas DataFrame and Series**

Pandas is a powerful data manipulation library in python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A series os one-dimensional array-like object, while a DataFrame is two-dimensional, size-mutable, and potentially heterogenous tabular data structure with labeled axes (rows and columns).

In [1]:
print("hello world")

hello world

In [2]:
import pandas as pd

In [3]:
# Series (1D array like object that can hold any data type. it is similar to a column in a table.)

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n", series)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# Create series from dictionary
data = {"a": 1, "b":2, "c":3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data = [10,20,30]
index = ["a", "b","c"]
pd.Series(data, index = index)

a    10
b    20
c    30
dtype: int64

In [8]:
# DataFrame
#  Create a dataframe from a dictionary of list

data = {
    "Name" :["Krisha","Palak","Guman"],
    "Age":[25,30,45],
    "City": ["Banglore", "Pune", "Mumbai"]
}
df= pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age      City
0  Krisha   25  Banglore
1   Palak   30      Pune
2   Guman   45    Mumbai
<class 'pandas.core.frame.DataFrame'>

In [9]:
import numpy as np
np.array(df)

array([['Krisha', 25, 'Banglore'],
       ['Palak', 30, 'Pune'],
       ['Guman', 45, 'Mumbai']], dtype=object)

In [16]:
#  Create a DataFrame from a list of dictionaries
data = [
    {"Name":"Krisha","Age":22, "City": "Mumbai"},
    {"Name":"Palak","Age":30, "City": "Pune"},
    {"Name":"Guman","Age":45, "City": "Banglore"}
]
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age      City
0  Krisha   22    Mumbai
1   Palak   30      Pune
2   Guman   45  Banglore
<class 'pandas.core.frame.DataFrame'>

In [40]:
df = pd.read_csv("data.csv")
print(df.head(5))
print(df.tail(5))

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [17]:
# Accessing data in DataFrame
df

     Name  Age      City
0  Krisha   22    Mumbai
1   Palak   30      Pune
2   Guman   45  Banglore

In [18]:
df["Name"]

0    Krisha
1     Palak
2     Guman
Name: Name, dtype: object

In [21]:
df.loc[0][0] # Access the first row

C:\Users\Krisha Ebrahimpurkar\AppData\Local\Temp\ipykernel_1120\3926507563.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0] # Access the first row

'Krisha'

In [22]:
df.iloc[0][2]

C:\Users\Krisha Ebrahimpurkar\AppData\Local\Temp\ipykernel_1120\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Mumbai'

In [26]:
# Accessing a specified element
df.at[1,"Age"]
df.iat[2,2]

'Banglore'

In [27]:
# Data Manipulation with DataFrame
df

     Name  Age      City
0  Krisha   22    Mumbai
1   Palak   30      Pune
2   Guman   45  Banglore

In [29]:
df["Salary"]=[50000, 60000, 70000]
df

     Name  Age      City  Salary
0  Krisha   22    Mumbai   50000
1   Palak   30      Pune   60000
2   Guman   45  Banglore   70000

In [33]:
# if we do only df.drop("salary") it wont work because we need to specify the axis. axis = 0 means row and axis = 1 means column.
# but not a permenant operation 
# therefore we have to assign it to a new variable or use inplace = True
df.drop("Salary", axis = 1, inplace = True)

In [34]:
df

     Name  Age      City
0  Krisha   22    Mumbai
1   Palak   30      Pune
2   Guman   45  Banglore

In [35]:
# Add age to column
df["Age"]= df["Age"]+1
df

     Name  Age      City
0  Krisha   23    Mumbai
1   Palak   31      Pune
2   Guman   46  Banglore

In [38]:
df.drop(0)

    Name  Age      City
1  Palak   31      Pune
2  Guman   46  Banglore

In [39]:
df

     Name  Age      City
0  Krisha   23    Mumbai
1   Palak   31      Pune
2   Guman   46  Banglore

In [42]:
# Display the data type of each column
print("Data types: \n", df.dtypes)

# Describe the DataFrame
print("Statistical Summary: \n", df.describe())

# Group by a column and perform an aggregation
grouped = df.groupby("Category")["Value"].mean()
print("Mean value by Category:\n", grouped)

Data types:
 Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object
Statistical Summary:
            Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000
Mean value by Category:
 Category
A    48.357143
B    44.142857
C    59.842105
Name: Value, dtype: float64

In [44]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000